DROP TABLE IF EXISTS STUDENT;
DROP TABLE IF EXISTS INSTRUMENT;
DROP TABLE IF EXISTS COMPOSITION;
DROP TABLE IF EXISTS PERFORMANCE_PARTICIPANTS;





CREATE TABLE INSTRUMENT (
       ID INT NOT NULL AUTO_INCREMENT
     , INSTRUMENT_TYPE VARCHAR(15) NOT NULL
     , PRODUCER VARCHAR(30) NOT NULL
     , PROD_DATE DATE
     , PURCH_DATE DATE
     , PRIMARY KEY (ID)
);

CREATE TABLE STUDENT (
       ID INT NOT NULL AUTO_INCREMENT
     , FIRST_NAME VARCHAR(60) NOT NULL
     , LAST_NAME VARCHAR(40) NOT NULL
     , BIRTH_DATE DATE
     , INSTRUMENT_ID INT NOT NULL
     , PRIMARY KEY (ID)
     , UNIQUE UQ_CONTACT_1 (FIRST_NAME, LAST_NAME)
     , CONSTRAINT FK_STUDENT_1 FOREIGN KEY (INSTRUMENT_ID)
       REFERENCES INSTRUMENT (ID)
);

CREATE TABLE COMPOSITION (
       ID INT NOT NULL AUTO_INCREMENT
     , TITLE VARCHAR(15) NOT NULL
     , AUTHOR VARCHAR(30) NOT NULL
     , PRIMARY KEY (ID)
);

CREATE TABLE PERFOMANCE_PARTICIPANS (
      COMPOSITION_ID INT NOT NULL
     , STUDENT_ID INT NOT NULL
     , PRIMARY KEY (COMPOSITION_ID, STUDENT_ID)
     , CONSTRAINT FK_PERFOMANCE_PARTICIPANS_1 FOREIGN KEY (COMPOSITION_ID)
                  REFERENCES COMPOSITION (ID) ON DELETE CASCADE
     , CONSTRAINT FK_PERFOMANCE_PARTICIPANS_2 FOREIGN KEY (STUDENT_ID)
                  REFERENCES STUDENT (ID)
);
